// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateTodo struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Content   *string   `json:"content,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy string    `json:"createdBy"`
}

type UpdateTodo struct {
	Content *string `json:"content,omitempty"`
	Title   *string `json:"title,omitempty"`
}
